spring.application.name=Inspire-customer-relationship-management

# ==============================
# DATABASE CONFIGURATION
# ==============================
spring.datasource.url=jdbc:mysql://localhost:3306/crm_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Rahul2140@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================
# JPA / HIBERNATE CONFIGURATION
# ==============================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


# ==============================
# SERVER CONFIG
# ==============================
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rahulmali2140@gmail.com
spring.mail.password=iexn qkvr uach jjfw

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#Rahulmali1234@

jwt.secret=9mG7X5wGq8ZtL1f3rX9YbQ2sKp3vH1cJdF4aV6nR8oU=


